data:
    input: 'data.extxyz'  # path (usually extxyz) for target calculation
    input_args:  # this will pass to ase.io.read
        format: 'extxyz'
        index: ':'

calculator:
    calc_type: 'sevennet'  # sevennet, sevennet-batch, custom
    path: '/data2/shared_data/cps/omni/oob_v6/checkpoint_1.pth'  
    calc_args:  
        modal: 'omat24' # matpes_r2scan
    # batch_size: 10  # for sevennet batch calculator, set batch size
    # avg_atom_num: 10  # for sevennet batch calculator, set avg # of atoms in each batch

relax:
    save: ./relax
    # load: ./relax
    cont: False
    args:
        fmax: 1e-05
        steps: 4000  
        opt: 'bfgs'
        cell_filter: 'unitcell'
        fix_symm: True
        log: '.relax/ase_relax.log' 

phonon:
    save: ./phonon
    # load: 
fc2:
    save: ./fc2
    # load: 
    symm: True
fc3:
    save: ./fc3
    # load: 
    displacement: 0.03  # in Angstrom
    symm: True

    
cond:
    save: ./cond
    cond_type: 'bte'  # [bte, wte]
    temperature: 300  
    is_isotope: False  # whether consider isotope effect
    is_LBTE: True  # RTA; False, direct solution by LBTE True
    ## convergence has to be false
    ## condtype has to be in bte, wte
    ## shengbte can only do bte
